In [1]:
import numpy as np

In [2]:
np.empty(10)

array([6.91143597e-310, 4.68559461e-310, 6.91141260e-310, 6.91143617e-310,
       6.91143493e-310, 6.91143617e-310, 4.68559383e-310, 6.91141259e-310,
       6.91141260e-310, 6.91143616e-310])

In [3]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [5]:
x=np.arange(10,50)

In [6]:
x.shape

(40,)

In [7]:
x.dtype

dtype('int64')

In [8]:
np.__version__

'1.19.2'

In [9]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/umar/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/umar/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/umar/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/umar/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/umar/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/umar/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/umar/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/umar/anaconda3/include']


In [10]:
x.ndim

1

In [13]:
np.zeros((2,2), dtype=bool)

array([[False, False],
       [False, False]])

In [22]:
np.full((2,2), True)

array([[ True,  True],
       [ True,  True]])

In [26]:
z=np.arange(0,10)
z.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
z.reshape(1,5,2)

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [31]:
z=np.arange(0,20).reshape(2,10)
np.flip(z)

array([[19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [34]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [36]:
##The identity array is a square array with ones on the main diagonal.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
arr = np.array([1, 2, 3, 4, 5])

arr.astype('float64')

array([1., 2., 3., 4., 5.])

In [43]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [45]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1==arr2

array([[False, False, False],
       [False, False, False]])

In [48]:
x=np.arange(0,9)
x[x%2==1] ##dispalying indexes that fullfil condition

array([1, 3, 5, 7])

In [50]:
x[x%2==1]=-1 ##replaciing indexes with -1 that fulfil this condition
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [53]:
arr = np.arange(10)

arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [59]:
x=np.ones((6,6))
x[1:5, 1:5]=0
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [61]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

In [63]:
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [68]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,:4]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
x=np.arange(0,9).reshape(3,3)
x[0]

array([0, 1, 2])

In [89]:
x=np.arange(0,9).reshape(3,3)
x[1,1]

4

In [86]:
x=np.arange(0,9).reshape(3,3)
x[0:2,2]


array([2, 5])

In [94]:
x=np.random.rand(10,10)
x

array([[0.46514099, 0.06277154, 0.88662864, 0.0269142 , 0.42499813,
        0.62396769, 0.86627069, 0.7261146 , 0.26677664, 0.78836344],
       [0.01956362, 0.34831544, 0.56179297, 0.08871738, 0.04513671,
        0.69059919, 0.70394609, 0.00520522, 0.99081797, 0.29971391],
       [0.66397746, 0.83231349, 0.88478858, 0.21710734, 0.97702664,
        0.67853064, 0.23937785, 0.87826378, 0.38933753, 0.6559643 ],
       [0.86866945, 0.56790583, 0.28233846, 0.34939418, 0.15272829,
        0.41963283, 0.13047806, 0.77752013, 0.05132437, 0.15654496],
       [0.58404665, 0.0033954 , 0.84985762, 0.65409682, 0.42832952,
        0.68127076, 0.22265193, 0.45907446, 0.74802873, 0.67317048],
       [0.74080466, 0.13028046, 0.80346432, 0.04934126, 0.70493445,
        0.50272042, 0.58162125, 0.90987186, 0.09669554, 0.92187547],
       [0.57727626, 0.06890227, 0.33782144, 0.27318857, 0.00537884,
        0.83922198, 0.46897887, 0.68040365, 0.89125535, 0.11054015],
       [0.12981469, 0.44008859, 0.3141758

In [95]:
np.max(x)

0.9908179692384719

In [96]:
np.min(x)

0.003395404677573821

In [98]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
             ##finding common elements in two arrays
    
np.intersect1d(a,b)

array([2, 4])

In [101]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
##Find the positions where elements of a and b match

np.searchsorted(a,np.intersect1d(a,b))
##output gives position of elements common in both and at same position

array([1, 5])

In [107]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.rands(names)
data

##Find all the values from array data where the values from array names are not equal to Will

AttributeError: module 'numpy.random' has no attribute 'rands'

In [108]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

SyntaxError: invalid syntax (<ipython-input-108-53ef7a6d4f8e>, line 1)

# HARD

In [114]:
z=np.arange(0,15).reshape(5,3)
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [117]:
np.around(z,decimals=3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [119]:
z=np.arange(0,16).reshape(2,2,4)
z

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [120]:
np.around(z, decimals=3)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [122]:
##swap axes

np.swapaxes(z,0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [130]:
z=np.arange(10)
#finding square root of each element
y=np.sqrt(z)
y[y<0.5]=0
y

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [136]:
x=np.arange(0,12)
y=np.arange(12,24)
##making array that has maximum values of both arrays
z=np.maximum(x,y)
z

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [139]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.unique(names) ##find unique data and sort them

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [144]:
a = np.array([1,2,3,4,5]) 

b = np.array([5,6,7,8,9])

##remove items in a that are also in b

##comons
c=np.intersect1d(a,b)

##delete common from a
np.delete(a[x]==c)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [154]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

##insert newcolumn at column 2 of samplearray

newColumn = np.array([[10,10,10]])

sampleArray[:3,1]= newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [155]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 

y = np.array([[6., 23.], [-1, 7], [8, 9]])

##finding dot product

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [158]:
a= np.arange(0,20).reshape(5,4)
np.cumsum(a)




array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190])